# Spring2885 Backend API.
swagger: '2.0'

# This is your document metadata
info:
  version: "0.0.1"
  title: NDNU Community Access API
  description: An API for the Spring2885 FrontEnd.
  contact: 
    name: Spring2885 Backend Development Team
    email: api@spring-2885.org
    url: https://github.com/rob2885/backend
  

# Describe your paths here
paths:
  /newuser:
    post:
      tags: ["User"]
      description: |
        Creates a new user in the system
      description: |
      parameters:
        - name: email
          in: formData
          description: The email address to use for the new person.
          required: true
          type: string
          format: email
        - name: password
          in: formData
          description: the unencrypted password to use
          required: true
          type: string
          format: password
      responses:
        200:
          description: Creates a new person in the system.
        500:
          description: An error creating the user.

  # This is the /profiles endpoint
  /api/v1/profiles:
    # This is a HTTP operation
    get:
      tags: ["Profiles"]
      # Describe this verb here. Note: you can use markdown
      summary: |
        Fetches all `profile` objects
      description: |
        Fetches all `profile` objects. up to **size** if specified
        otherwise fetches all objects.
      # This is array of GET operation parameters:
      parameters:
        # An example parameter that is in query and is required
        -
          name: size
          in: query
          description: The maxinum number of profiles to fetch.
          required: false
          type: number
          format: int32
      # Expected responses for this operation:
      responses:
        # Response code
        200:
          description: Successful response
          # A schema describing your response object.
          # Use JSON Schema format
          schema:
            type: array
            items:
              $ref: '#/definitions/person'

  /api/v1/profiles/{id}:
    get:
      tags: ["Profiles"]
      summary: |
        Fetches the `profile` for id `id`.
      description: |
      parameters:
        - name: id
          in: path
          description: The ID of the profile to fetch
          required: true
          type: number
          format: int32
      responses:
        # Response code
        200:
          description: Successful response
          # A schema describing your response object.
          # Use JSON Schema format
          schema:
            $ref: '#/definitions/person'
    put:
      tags: ["Profiles"]
      summary: |
          The profile to update.
      parameters:
        - name: id
          in: path
          description: The ID of the profile to fetch
          required: true
          type: number
          format: int32
        - name: person
          in: body
          description: The profile to update.
          schema:
            $ref: '#/definitions/person'
          required: true
      responses:
        200:
          description: Updates the person
    delete:
      tags: ["Profiles"]
      summary: |
        The profile to delete.
      parameters:
        - name: id
          in: path
          description: The profile to delete.
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: Updates the person.
        500:
          description: Error deleting the profile "ID".
  /api/v1/jobs:
    get:
      tags: ["Jobs"]
      # Describe this verb here. Note: you can use markdown
      description: |
        Gets `Job` objects.
        Optional query param of **size** determines
        size of returned array
      # This is array of GET operation parameters:
      parameters:
        # An example parameter that is in query and is required
        -
          name: size
          in: query
          description: Size of array
          required: true
          type: number
          format: double
      # Expected responses for this operation:
      responses:
        # Response code
        200:
          description: Successful response
          # A schema describing your response object.
          # Use JSON Schema format
          schema:
            type: array
            items:
              $ref: '#/definitions/Job'
    post:
      tags: ["Jobs"]
      parameters:
        - name: Job
          in: body
          description: The Job you want to post
          schema:
            $ref: '#/definitions/Job'
          required: true
      responses:
        200:
          description: Make a new Job
    put:
      tags: ["Jobs"]
      parameters:
        - name: job
          in: body
          description: The Job you want to update
          schema:
            $ref: '#/definitions/Job'
          required: true
      responses:
        200:
          description: Updates the Job
definitions:
  person:
    type: object
    properties:
      id: 
        type: integer
        format: int64
      name:
        type: string
      student_id:
        type: integer
        format: int32
      title:
        type: string
      about_me:
        type: string
      resume_url:
        type: string
      image_url:
        type: string
      email: 
        type: string
      phone:
        type: string
      occupation:
        type: string
      company_name:
        type: string
      birthdate:
        type: string
        format: date
      variety:
        type: string #as in alum, faculty, student
      last_login_date:
        type: string
        format: date
  Job:
    type: object
    properties:
      id: 
        type: integer
        format: int64
      description:
        type: string
      job_type:
        type: string
  News:
    type: object
    properties:
      id:
        type: integer
        format: int64
      description:
        type: string
      news title:
        type: string
tags:
  - name: User
    description: Everything to do with User
  - name: Profiles
    description: Fetch, Delete, and update Profiles
    
